
export const HIDE_LOADING='HIDE_LOADING';
export const SHOW_LOADING='SHOW_LOADING';

export const FOOTER_SHOW='FOOTER_SHOW';
export const FOOTER_HIDE='FOOTER_HIDE';
export const USER_SIGNIN='USER_SIGNIN';
export const USER_SIGNOUT='USER_SIGNOUT';